# Generated by Django 5.2.7 on 2025-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='descrition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
