# Generated by Django 5.2.7 on 2025-10-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_student_descrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='descrition',
            field=models.FileField(upload_to=''),
        ),
    ]
