# Generated by Django 5.2.7 on 2025-10-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_settings_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=5, verbose_name='Название'),
        ),
    ]
