# Generated by Django 5.2.7 on 2025-11-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_settings_facebook_alter_settings_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='work_time',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
