# Generated by Django 5.2.7 on 2025-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_settings_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='work_time',
            field=models.CharField(max_length=30, verbose_name='Рабочее время'),
        ),
    ]
